"""add ad_type column and subscription_channels table

Revision ID: 207225416c5e
Revises: 888f01305d7d
Create Date: 2026-04-08 16:02:59.697591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207225416c5e'
down_revision: Union[str, Sequence[str], None] = '888f01305d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type first (needed for PostgreSQL)
    op.execute("CREATE TYPE adtype AS ENUM ('BROADCAST', 'POST_DOWNLOAD')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_username', sa.String(length=128), nullable=True),
    sa.Column('channel_title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('REQUIRED', 'OPTIONAL', name='subscriptionstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_subscription_channels_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_channels'))
    )
    op.create_index(op.f('ix_subscription_channels_bot_id'), 'subscription_channels', ['bot_id'], unique=False)
    op.add_column('ads', sa.Column('ad_type', sa.Enum('BROADCAST', 'POST_DOWNLOAD', name='adtype'), nullable=False, server_default='BROADCAST'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'ad_type')
    op.drop_index(op.f('ix_subscription_channels_bot_id'), table_name='subscription_channels')
    op.drop_table('subscription_channels')
    op.execute("DROP TYPE adtype")
    # ### end Alembic commands ###
