"""Update admin roles media metadata and cache rotation

Revision ID: 344f8ad00781
Revises: 444adf094734
Create Date: 2026-04-08 00:23:48.760130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344f8ad00781'
down_revision: Union[str, Sequence[str], None] = '444adf094734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_channels',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Человекочитаемое название канала'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Username канала без символа @'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Числовой Telegram ID канала'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание или заметки о канале'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Используется ли канал для кэширования'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Когда в последний раз использовали этот канал для загрузки'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_channels')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_cache_channels_telegram_id')),
    sa.UniqueConstraint('username', name=op.f('uq_cache_channels_username'))
    )
    op.add_column('media', sa.Column('platform_icon', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('file_count', sa.Integer(), nullable=False))
    op.add_column('media', sa.Column('media_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'media_info')
    op.drop_column('media', 'file_count')
    op.drop_column('media', 'platform_icon')
    op.drop_table('cache_channels')
    # ### end Alembic commands ###
